path: /home/s0433/local/data/exdark_yolo # dataset root dir
train: images/train # train images (relative to 'path') 66000 images
val: images/val # val images (relative to 'path') 11000 images
test: images/test # test images (optional)hard_im part 2132 images

names:

    0: Bicycle,
    1: Boat,
    2: Bottle,
    3: Bus,
    4: Car,
    5: Cat,
    6: Chair,
    7: Cup,
    8: Dog,
    9: Motorbike,
    10: People,
    11: Table,
