
path: /home/s0433/local/data/speedplusv2/synthetic/yolo_box # dataset root dir
train: images/val # train images (relative to 'path') 66000 images
val: images/val # val images (relative to 'path') 11000 images
test: # test images (optional)hard_im part 2132 images

names:

  0:
  1: tango